version: '2'
services:
  elasticsearch:
    image: "elasticsearch:2.4.1"
    volumes:
     - $PWD/elasticsearch/data:/usr/share/elasticsearch/data
     - $PWD/elasticsearch/config:/usr/share/elasticsearch/config
     - $PWD/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
     - "9200:9200"
     - "9300:9300"
  hanlp-api:
    image: "samurais/hanlp-api:2.0.0"
    ports:
     - "3007:3000"